Tags:
  Name: Brighid Commands
  Owner: Cythral
  Contact:Name: Talen Fisher
  Contact:Email: talen.fisher@cythral.com

Parameters:
  EnvironmentName:
    Development: dev
    Production: prod

  DomainName:
    Development: commands.dev.brigh.id
    Production: commands.brigh.id

  DatabaseHost:
    Development: db.dev.brigh.id
    Production: db.brigh.id

  DatabaseUser:
    Development: brighid-commands
    Production: brighid-commands

  DatabaseName:
    Development: brighid-commands
    Production: brighid-commands

  DatabasePassword:
    Development: AQICAHjCPp/4JJqnSjdP1A4JZ+E3yC2Gqmk9GshiMiqu57jujwG1ay6aLj6UdPxsd3Krb78bAAAAczBxBgkqhkiG9w0BBwagZDBiAgEAMF0GCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMgop9c6x0m3vxCpdTAgEQgDCdLC0bmInFoRZm1F0zexSOGRZY/WhYYTO0g83YjCj9yRmpcCdHSIS/ZGKRvPkhxGo=
    Production: AQICAHj/2SUStzyXNMLx0/GX2lnjChwPoR4BUvoYRIybQNwYyQGdj9szLLnZfFzppIvTqsd7AAAAcjBwBgkqhkiG9w0BBwagYzBhAgEAMFwGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM9L/bzYvrFU5E0DWoAgEQgC8cLQ/kOYpl6A9C1C5sTrZMeLmhw1I6ZAWijjLWnYNb5UFJSAS5Vfq7SPj+AUiOCw==

  OpenIdMetadataAddress:
    Development: http://identity.dev.brigh.id/.well-known/openid-configuration
    Production: http://identity.brigh.id/.well-known/openid-configuration

  IdentityServiceUri:
    Development: identity.dev.brigh.id
    Production: identity.brigh.id

  EnvoyImage:
    Development: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:arm64-v1.22.2.0-prod
    Production: 840364872350.dkr.ecr.us-east-1.amazonaws.com/aws-appmesh-envoy:arm64-v1.22.2.0-prod

  MeshNodeName:
    Development: commands-dev
    Production: commands-prod

  XrayImage:
    Development: public.ecr.aws/xray/aws-xray-daemon:3.3.3
    Production: public.ecr.aws/xray/aws-xray-daemon:3.3.3

  RecaptchaSiteKey:
    Development: 6LcZKiclAAAAAN8fC7p5NEhKirMr1hN1qFJhiIvU
    Production: 6LcZKiclAAAAAN8fC7p5NEhKirMr1hN1qFJhiIvU

  RecaptchaSecretKey:
<<<<<<< Updated upstream
    Development: AQICAHgoCT+foL9Va61ILjex5kDLFnI+2BcWncYg6XnZcbrkEgEoeh1+VKpTiGa6Peeeap7MAAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDAh2QGmWVDYJnOg/tQIBEIBDynyMNGyDKD3u+PS2mSUaAKi6HxSzsumPMXTJ4R/T+rI4jAarBMl3iJwsA011YKvdH5RkNrXcBFWGvu+2PCEEgmoVYg==
    Production: AQICAHi54q7lId3MD/Ui1K7aSfISd7MAgfjYVA3TKglV1sj1yAFWNMimZcsyMuvNi0kc/fJfAAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDJp9XBtP05Vc3KvCoAIBEIBDcln397XIvPPyjDAjwoDA5biT3m9T6cERo3SCBhA85o2HNizJo3P9hEK0X/pGKxTpB9IdDEzFSwULQCKObkGJm5ptxw==
=======
    Development: AQICAHgoCT+foL9Va61ILjex5kDLFnI+2BcWncYg6XnZcbrkEgFv9hsc9V3bFIY0OifmMsXkAAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDGDzMPr9x22H/9/FIQIBEIBDICbxvomjwo7IWlEMIAaL5X8nf006VWIEDAjQVCCqpK0QGsBGrzGn1ZylsZFOukNzSwYzCIFtKcelnBTtc7I4vUYTDQ==
    Production: AQICAHi54q7lId3MD/Ui1K7aSfISd7MAgfjYVA3TKglV1sj1yAFii1ZXw3KrmB+iTQQMC6RcAAAAhzCBhAYJKoZIhvcNAQcGoHcwdQIBADBwBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDDQ4Cu7p27L4llAruQIBEIBD0x4rAz5StmfBWaE40gtiSlWPyGRj6NoW15K6oneppCiDNiedDu5g0ykq8iu7H9lIUjB3VH1B+k5IpK6JFeQ/lMou5Q==
>>>>>>> Stashed changes
