name: Notifications
on: deployment_status
jobs:
  approval-request:
    runs-on: ubuntu-latest
    if: ${{ github.event.deployment_status.state == 'waiting' && github.event.deployment.environment == 'Production' }}
    steps:
      - name: Request Deployment Approval
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: |
            [
              {
                "title": "[${{ github.repository }}] Requires Deployment Approval",
                "url": "${{ github.event.deployment_status.target_url }}",
                "description": "${{ github.repository }} requires approval for deployment to production.",
                "color": 15105570
              }
            ]
