name: Notifications
on: deployment_status
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Request Deployment Approval
        uses: Ilshidur/action-discord@master
        if: ${{ github.event.deployment_status.state == 'waiting' && github.event.deployment.environment == 'Production' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: |
            [
              {
                "title": "[${{ github.repository }}] Requires Deployment Approval",
                "url": "${{ github.event.deployment_status.target_url }}",
                "description": "**${{ github.repository }}** requires approval for deployment to production.\n**Changes:** ${{ github.event.deployment.description }}",
                "color": 15105570
              }
            ]

      - name: Notify Deployment Success
        uses: Ilshidur/action-discord@master
        if: ${{ github.event.deployment_status.state == 'active' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: |
            [
              {
                "title": "[${{ github.repository }}] Successfully Deployed to ${{ github.event.deployment.environment }}",
                "url": "${{ github.event.deployment_status.target_url }}",
                "description": "Successfully deployed **${{ github.repository }}** to ${{ github.event.deployment.environment }}.\n**Changes:** ${{ github.event.deployment.description }}",
                "color": 3066993
              }
            ]

      - name: Notify Deployment Failure
        uses: Ilshidur/action-discord@master
        if: ${{ github.event.deployment_status.state == 'failure' }}
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_EMBEDS: |
            [
              {
                "title": "[${{ github.repository }}] ${{ github.event.deployment.environment }} Deployment Failure",
                "url": "${{ github.event.deployment_status.target_url }}",
                "description": "**${{ github.repository }}** failed to deploy to ${{ github.event.deployment.environment }}.\n**Changes:** ${{ github.event.deployment.description }}",
                "color": 12720135
              }
            ]

  success-notification:
    runs-on: ubuntu-latest
    if: ${{ github.event.deployment_status.state == 'failure' }}
    steps:
      - name: Notify Deployment Success
        uses:

  failure-notification:
    runs-on: ubuntu-latest

    steps:
