name: Update Client
on:
  workflow_call:
    inputs:
      version:
        description: The version of the client to use.
        type: string
        required: true

      artifacts-location:
        description: S3 URL to look for deployment artifacts at.
        type: string
        required: true

jobs:
  update-client:
    runs-on: ubuntu-latest
    concurrency: update-client
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_SHARED_ROLE }}
          aws-region: us-east-1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1

      - name: Display .NET Info
        run: dotnet --info

      - name: Update Client
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          dotnet run \
            --project cicd/Cicd.ClientUpdateDriver/Cicd.ClientUpdateDriver.csproj -- \
            --artifacts-location ${{ inputs.artifacts-location }} \
            --version ${{ inputs.version }}
